### ISSUE TITLE
Colouring lakes separately when imposing a transparent background

### ISSUE THREAD

**Issue by chriberfra** [whocov/whomapper#8]
Hey hey - thanks for providing this great package. Super, super useful. 

My challenge is regarding the colouring of the lakes. The eventual map will have a transparent background and the lakes need to be coloured accordingly. In my case, the slide background is dark blue (#00205C) and I would like to colour the lakes in the same colour. 

I can see that the function who_map_disp appears to have everything I need. However, I am not able to change anything there.  Would it be possible to integrate a "feature" to control this small piece?

**Comment by henryls1** [comment]
Addressed in latest commit to main
